/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KcalCalcPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var USDA_SEARCH_URL = "https://api.nal.usda.gov/fdc/v1/foods/search";
var ENERGY_NUTRIENT_ID = 1008;
var PROTEIN_NUTRIENT_ID = 1003;
var FAT_NUTRIENT_ID = 1004;
var CARBS_NUTRIENT_ID = 1005;
var DEFAULT_INGREDIENT_DELIMITER = " - ";
var TOTAL_LINE_REGEX = /^\s*<u>(?:Total kcal|Section kcal): .+<\/u>\s*$/i;
var HEADING_REGEX = /^#{1,6}\s+.+$/;
var LOW_CONFIDENCE_THRESHOLD = 0.75;
var DEFAULT_SETTINGS = {
  usdaApiKey: "",
  ingredientDelimiter: DEFAULT_INGREDIENT_DELIMITER,
  includeMacros: true,
  addSectionTotals: true,
  showMatchPreview: true,
  markLowConfidenceMatches: true,
  preferredFoods: ""
};
function parseSettings(data) {
  if (!isRecord(data)) {
    return {};
  }
  return {
    usdaApiKey: readString(data, "usdaApiKey"),
    ingredientDelimiter: readString(data, "ingredientDelimiter"),
    includeMacros: readBoolean(data, "includeMacros"),
    addSectionTotals: readBoolean(data, "addSectionTotals"),
    showMatchPreview: readBoolean(data, "showMatchPreview"),
    markLowConfidenceMatches: readBoolean(data, "markLowConfidenceMatches"),
    preferredFoods: readString(data, "preferredFoods")
  };
}
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function readString(data, key) {
  const value = data[key];
  return typeof value === "string" ? value : void 0;
}
function readBoolean(data, key) {
  const value = data[key];
  return typeof value === "boolean" ? value : void 0;
}
function isKcalCalcSettingKey(key) {
  return key in DEFAULT_SETTINGS;
}
var KcalCalcPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lookupCache = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("calculator", "Annotate ingredient kcal", async () => {
      await this.annotateActiveMarkdownNote();
    });
    this.addCommand({
      id: "annotate-ingredient-kcal",
      name: "Annotate ingredient kcal in active note",
      editorCallback: async (editor) => {
        await this.annotateEditor(editor);
      }
    });
    this.addSettingTab(new KcalCalcSettingTab(this.app, this));
  }
  async loadSettings() {
    const savedData = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...parseSettings(savedData)
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  clearLookupCache() {
    this.lookupCache.clear();
  }
  async annotateActiveMarkdownNote() {
    const activeLeaf = this.app.workspace.activeEditor;
    const editor = activeLeaf == null ? void 0 : activeLeaf.editor;
    if (!editor) {
      new import_obsidian.Notice("Open a Markdown note before annotating kcal.");
      return;
    }
    await this.annotateEditor(editor);
  }
  async annotateEditor(editor) {
    var _a, _b;
    if (!this.settings.usdaApiKey.trim()) {
      new import_obsidian.Notice("Add your USDA FoodData Central API key in Kcal Calc settings.");
      return;
    }
    try {
      const result = await this.annotateText(editor.getValue());
      if (result.annotatedLines === 0) {
        new import_obsidian.Notice(`No ingredient lines found. Use: dark chocolate${this.getIngredientDelimiter()}200g`);
        return;
      }
      if (this.settings.showMatchPreview) {
        const shouldApply = await new MatchPreviewModal(this.app, result, this.settings.includeMacros).openAndWait();
        if (!shouldApply) {
          new import_obsidian.Notice("Kcal annotation cancelled.");
          return;
        }
      }
      editor.setValue(result.annotatedText);
      const skippedText = result.skippedFoods.length > 0 ? ` Skipped: ${result.skippedFoods.join(", ")}.` : "";
      new import_obsidian.Notice(`Annotated ${result.annotatedLines} line(s), total ${formatKcal((_b = (_a = result.totalNutrition) == null ? void 0 : _a.kcal) != null ? _b : result.totalKcal)} kcal.${skippedText}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Kcal Calc failed: ${message}`);
    }
  }
  async annotateText(text) {
    const newline = text.includes("\r\n") ? "\r\n" : "\n";
    const lines = text.split(/\r?\n/);
    const ingredientDelimiter = this.getIngredientDelimiter();
    const preferredFoods = parsePreferredFoods(this.settings.preferredFoods);
    const annotatedLines = [];
    const skippedFoods = [];
    const ingredients = [];
    const totalNutrition = createEmptyTotals();
    let sectionNutrition = createEmptyTotals();
    let changedLineCount = 0;
    let sectionHasHeading = false;
    let sectionAnnotatedLines = 0;
    const pushSectionTotal = () => {
      if (!this.settings.addSectionTotals || !sectionHasHeading || sectionAnnotatedLines === 0) {
        return;
      }
      if (annotatedLines.length > 0 && annotatedLines[annotatedLines.length - 1].trim() !== "") {
        annotatedLines.push("");
      }
      annotatedLines.push(`<u>Section kcal: ${formatNutritionTotals(sectionNutrition, this.settings.includeMacros)}</u>`);
      sectionNutrition = createEmptyTotals();
      sectionAnnotatedLines = 0;
    };
    for (const line of lines) {
      if (TOTAL_LINE_REGEX.test(line)) {
        continue;
      }
      if (HEADING_REGEX.test(line)) {
        pushSectionTotal();
        annotatedLines.push(line);
        sectionHasHeading = true;
        sectionNutrition = createEmptyTotals();
        sectionAnnotatedLines = 0;
        continue;
      }
      const ingredientLine = parseIngredientLine(line, ingredientDelimiter);
      if (!ingredientLine) {
        annotatedLines.push(line);
        continue;
      }
      const lookup = await this.findFoodNutrition(ingredientLine.foodName, preferredFoods);
      if (lookup === null) {
        skippedFoods.push(ingredientLine.foodName);
        annotatedLines.push(line);
        continue;
      }
      const nutrition = scaleNutrition(lookup.nutritionPer100g, ingredientLine.grams);
      addNutrition(totalNutrition, nutrition);
      addNutrition(sectionNutrition, nutrition);
      changedLineCount += 1;
      sectionAnnotatedLines += 1;
      ingredients.push({
        inputName: ingredientLine.foodName,
        lookup,
        nutrition
      });
      annotatedLines.push(formatIngredientLine(ingredientLine, ingredientDelimiter, lookup, nutrition, this.settings));
    }
    pushSectionTotal();
    if (changedLineCount > 0) {
      if (annotatedLines.length > 0 && annotatedLines[annotatedLines.length - 1].trim() !== "") {
        annotatedLines.push("");
      }
      annotatedLines.push(`<u>Total kcal: ${formatNutritionTotals(totalNutrition, this.settings.includeMacros)}</u>`);
    }
    return {
      annotatedText: annotatedLines.join(newline),
      annotatedLines: changedLineCount,
      skippedFoods,
      totalKcal: totalNutrition.kcal,
      totalNutrition,
      ingredients
    };
  }
  async findFoodNutrition(foodName, preferredFoods) {
    var _a, _b;
    const preferredQuery = preferredFoods.get(normalizePreferredFoodKey(foodName));
    const searchQuery = preferredQuery != null ? preferredQuery : foodName;
    const cacheKey = `${normalizePreferredFoodKey(foodName)}\0${normalizePreferredFoodKey(searchQuery)}`;
    if (this.lookupCache.has(cacheKey)) {
      return (_a = this.lookupCache.get(cacheKey)) != null ? _a : null;
    }
    const searchParams = new URLSearchParams({
      api_key: this.settings.usdaApiKey.trim(),
      query: searchQuery,
      pageSize: "5"
    });
    const response = await (0, import_obsidian.requestUrl)({
      url: `${USDA_SEARCH_URL}?${searchParams.toString()}`,
      method: "GET"
    });
    if (response.status === 401 || response.status === 403) {
      throw new Error("USDA API key was rejected.");
    }
    if (response.status < 200 || response.status >= 300) {
      throw new Error(`USDA search returned HTTP ${response.status}.`);
    }
    const data = response.json;
    const lookup = findFirstNutritionResult((_b = data.foods) != null ? _b : [], searchQuery, preferredQuery !== void 0);
    this.lookupCache.set(cacheKey, lookup);
    return lookup;
  }
  getIngredientDelimiter() {
    return this.settings.ingredientDelimiter || DEFAULT_INGREDIENT_DELIMITER;
  }
};
var MatchPreviewModal = class extends import_obsidian.Modal {
  constructor(app, result, includeMacros) {
    super(app);
    this.result = result;
    this.includeMacros = includeMacros;
    this.resolved = false;
  }
  openAndWait() {
    this.open();
    return new Promise((resolve) => {
      this.resolveResult = resolve;
    });
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("kcal-calc-preview");
    contentEl.createEl("h2", { text: "Kcal Calc match preview" });
    contentEl.createEl("p", {
      text: `Review ${this.result.annotatedLines} USDA match(es) before updating the note.`
    });
    const table = contentEl.createEl("table");
    const header = table.createEl("thead").createEl("tr");
    ["Ingredient", "USDA match", "Nutrition", "Confidence"].forEach((label) => {
      header.createEl("th", { text: label });
    });
    const body = table.createEl("tbody");
    for (const ingredient of (_a = this.result.ingredients) != null ? _a : []) {
      const row = body.createEl("tr");
      row.createEl("td", { text: ingredient.inputName });
      row.createEl("td", {
        text: ingredient.lookup.usedPreferredFood ? `${ingredient.lookup.matchedDescription} (preferred: ${ingredient.lookup.searchQuery})` : ingredient.lookup.matchedDescription
      });
      row.createEl("td", { text: formatNutritionValues(ingredient.nutrition, this.includeMacros) });
      row.createEl("td", {
        text: ingredient.lookup.needsReview ? `Review (${formatConfidence(ingredient.lookup.confidence)})` : formatConfidence(ingredient.lookup.confidence)
      });
    }
    if (this.result.skippedFoods.length > 0) {
      const skipped = contentEl.createEl("p");
      skipped.addClass("kcal-calc-preview-warning");
      skipped.setText(`No kcal match found for: ${this.result.skippedFoods.join(", ")}.`);
    }
    contentEl.createEl("p", {
      text: `Total: ${formatNutritionTotals((_b = this.result.totalNutrition) != null ? _b : kcalOnlyTotal(this.result.totalKcal), this.includeMacros)}`
    });
    const actions = contentEl.createDiv({ cls: "kcal-calc-preview-actions" });
    const applyButton = actions.createEl("button", { text: "Apply" });
    applyButton.addClass("mod-cta");
    applyButton.addEventListener("click", () => this.finish(true));
    const cancelButton = actions.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => this.finish(false));
  }
  onClose() {
    if (!this.resolved) {
      this.finish(false);
    }
  }
  finish(shouldApply) {
    var _a;
    if (this.resolved) {
      return;
    }
    this.resolved = true;
    (_a = this.resolveResult) == null ? void 0 : _a.call(this, shouldApply);
    this.close();
  }
};
function findFirstNutritionResult(foods, searchQuery, usedPreferredFood) {
  var _a;
  for (const food of foods) {
    const nutritionPer100g = findNutritionValues(food);
    if (nutritionPer100g === null) {
      continue;
    }
    const matchedDescription = (_a = food.description) != null ? _a : searchQuery;
    const matchQuality = getMatchQuality(searchQuery, matchedDescription);
    return {
      matchedDescription,
      searchQuery,
      usedPreferredFood,
      nutritionPer100g,
      confidence: matchQuality.confidence,
      needsReview: matchQuality.needsReview
    };
  }
  return null;
}
function findNutritionValues(food) {
  const kcal = findNutrientValue(food, ENERGY_NUTRIENT_ID, "kcal");
  if (kcal === null) {
    return null;
  }
  return {
    kcal,
    protein: findNutrientValue(food, PROTEIN_NUTRIENT_ID, "g"),
    carbs: findNutrientValue(food, CARBS_NUTRIENT_ID, "g"),
    fat: findNutrientValue(food, FAT_NUTRIENT_ID, "g")
  };
}
function findNutrientValue(food, nutrientId, unitName) {
  var _a, _b;
  const nutrients = (_a = food.foodNutrients) != null ? _a : [];
  for (const nutrient of nutrients) {
    const value = typeof nutrient.value === "number" ? nutrient.value : typeof nutrient.amount === "number" ? nutrient.amount : null;
    if (nutrient.nutrientId === nutrientId && ((_b = nutrient.unitName) == null ? void 0 : _b.toLowerCase()) === unitName && value !== null) {
      return value;
    }
  }
  return null;
}
function scaleNutrition(nutritionPer100g, grams) {
  const scale = grams / 100;
  return {
    kcal: nutritionPer100g.kcal * scale,
    protein: scaleNullableMacro(nutritionPer100g.protein, scale),
    carbs: scaleNullableMacro(nutritionPer100g.carbs, scale),
    fat: scaleNullableMacro(nutritionPer100g.fat, scale)
  };
}
function scaleNullableMacro(value, scale) {
  return value === null ? null : value * scale;
}
function createEmptyTotals() {
  return {
    kcal: 0,
    protein: 0,
    carbs: 0,
    fat: 0
  };
}
function kcalOnlyTotal(kcal) {
  return {
    kcal,
    protein: 0,
    carbs: 0,
    fat: 0
  };
}
function addNutrition(total, nutrition) {
  var _a, _b, _c;
  total.kcal += nutrition.kcal;
  total.protein += (_a = nutrition.protein) != null ? _a : 0;
  total.carbs += (_b = nutrition.carbs) != null ? _b : 0;
  total.fat += (_c = nutrition.fat) != null ? _c : 0;
}
function parsePreferredFoods(preferredFoods) {
  const aliases = /* @__PURE__ */ new Map();
  const trimmedPreferredFoods = preferredFoods.trim();
  if (trimmedPreferredFoods.startsWith("{")) {
    try {
      const parsed = JSON.parse(trimmedPreferredFoods);
      if (!isRecord(parsed)) {
        return aliases;
      }
      for (const [alias, query] of Object.entries(parsed)) {
        if (typeof query === "string" && alias.trim() && query.trim()) {
          aliases.set(normalizePreferredFoodKey(alias), query.trim());
        }
      }
      return aliases;
    } catch (e) {
      return aliases;
    }
  }
  for (const line of preferredFoods.split(/\r?\n/)) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith("#")) {
      continue;
    }
    const separator = trimmedLine.includes("=>") ? "=>" : "=";
    const separatorIndex = trimmedLine.indexOf(separator);
    if (separatorIndex === -1) {
      continue;
    }
    const alias = trimmedLine.slice(0, separatorIndex).trim();
    const query = trimmedLine.slice(separatorIndex + separator.length).trim();
    if (alias && query) {
      aliases.set(normalizePreferredFoodKey(alias), query);
    }
  }
  return aliases;
}
function normalizePreferredFoodKey(value) {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}
function getMatchQuality(input, match) {
  const inputTokens = tokenizeForMatch(input);
  const matchTokens = tokenizeForMatch(match);
  if (inputTokens.length === 0 || matchTokens.length === 0) {
    return { confidence: 0, needsReview: true };
  }
  let matchedTokens = 0;
  let approximateMatches = 0;
  for (const inputToken of inputTokens) {
    if (matchTokens.includes(inputToken)) {
      matchedTokens += 1;
      continue;
    }
    if (matchTokens.some((matchToken) => areCloseTokens(inputToken, matchToken))) {
      matchedTokens += 1;
      approximateMatches += 1;
    }
  }
  const confidence = matchedTokens / inputTokens.length;
  return {
    confidence,
    needsReview: confidence < LOW_CONFIDENCE_THRESHOLD || approximateMatches > 0
  };
}
function tokenizeForMatch(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(/\s+/).map((token) => token.replace(/s$/, "")).filter((token) => token.length > 1);
}
function areCloseTokens(inputToken, matchToken) {
  if (inputToken.length < 4 || matchToken.length < 4) {
    return false;
  }
  return levenshteinDistance(inputToken, matchToken) / Math.max(inputToken.length, matchToken.length) <= 0.22;
}
function levenshteinDistance(left, right) {
  const distances = Array.from({ length: left.length + 1 }, (_, index) => index);
  for (let rightIndex = 1; rightIndex <= right.length; rightIndex += 1) {
    let previousDistance = distances[0];
    distances[0] = rightIndex;
    for (let leftIndex = 1; leftIndex <= left.length; leftIndex += 1) {
      const currentDistance = distances[leftIndex];
      const substitutionCost = left[leftIndex - 1] === right[rightIndex - 1] ? 0 : 1;
      distances[leftIndex] = Math.min(
        distances[leftIndex] + 1,
        distances[leftIndex - 1] + 1,
        previousDistance + substitutionCost
      );
      previousDistance = currentDistance;
    }
  }
  return distances[left.length];
}
var KcalCalcSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        name: "USDA API key",
        desc: "Used for FoodData Central ingredient searches.",
        control: {
          type: "text",
          key: "usdaApiKey",
          placeholder: "api.data.gov key"
        }
      },
      {
        name: "Ingredient delimiter",
        desc: "Separates the food name from the amount.",
        control: {
          type: "text",
          key: "ingredientDelimiter",
          placeholder: DEFAULT_INGREDIENT_DELIMITER
        }
      },
      {
        name: "Include macros",
        desc: "Add protein, carbs, and fat next to each kcal value when USDA provides them.",
        control: {
          type: "toggle",
          key: "includeMacros"
        }
      },
      {
        name: "Add section totals",
        desc: "Add an underlined section total before the next Markdown heading.",
        control: {
          type: "toggle",
          key: "addSectionTotals"
        }
      },
      {
        name: "Show match preview",
        desc: "Review USDA matches before the note is changed.",
        control: {
          type: "toggle",
          key: "showMatchPreview"
        }
      },
      {
        name: "Mark low-confidence matches",
        desc: "Append a review marker when the ingredient differs from the USDA match.",
        control: {
          type: "toggle",
          key: "markLowConfidenceMatches"
        }
      },
      {
        name: "Preferred foods",
        desc: "One alias per line, for example: whey = Whey protein powder",
        control: {
          type: "textarea",
          key: "preferredFoods",
          placeholder: "whey = Whey protein powder\ndark choc = Chocolate, dark, 70-85% cacao solids",
          rows: 6
        }
      }
    ];
  }
  getControlValue(key) {
    if (isKcalCalcSettingKey(key)) {
      return this.plugin.settings[key];
    }
    return void 0;
  }
  async setControlValue(key, value) {
    if (!isKcalCalcSettingKey(key)) {
      return;
    }
    if (key === "usdaApiKey" || key === "ingredientDelimiter" || key === "preferredFoods") {
      this.plugin.settings[key] = typeof value === "string" ? value : DEFAULT_SETTINGS[key];
    } else {
      this.plugin.settings[key] = typeof value === "boolean" ? value : DEFAULT_SETTINGS[key];
    }
    if (key === "usdaApiKey" || key === "preferredFoods") {
      this.plugin.clearLookupCache();
    }
    await this.plugin.saveSettings();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("USDA API key").setDesc("Used for FoodData Central ingredient searches.").addText((text) => {
      text.setPlaceholder("api.data.gov key").setValue(this.plugin.settings.usdaApiKey).onChange(async (value) => {
        this.plugin.settings.usdaApiKey = value.trim();
        this.plugin.clearLookupCache();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Ingredient delimiter").setDesc("Separates the food name from the amount. Spaces are kept exactly as typed.").addText((text) => {
      text.setPlaceholder(DEFAULT_INGREDIENT_DELIMITER).setValue(this.plugin.settings.ingredientDelimiter).onChange(async (value) => {
        this.plugin.settings.ingredientDelimiter = value || DEFAULT_INGREDIENT_DELIMITER;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Include macros").setDesc("Add protein, carbs, and fat next to each kcal value when USDA provides them.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.includeMacros).onChange(async (value) => {
        this.plugin.settings.includeMacros = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Add section totals").setDesc("Add an underlined section total before the next Markdown heading.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.addSectionTotals).onChange(async (value) => {
        this.plugin.settings.addSectionTotals = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Show match preview").setDesc("Review USDA matches before the note is changed.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showMatchPreview).onChange(async (value) => {
        this.plugin.settings.showMatchPreview = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Mark low-confidence matches").setDesc("Append a review marker when the ingredient differs from the USDA match.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.markLowConfidenceMatches).onChange(async (value) => {
        this.plugin.settings.markLowConfidenceMatches = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Preferred foods").setDesc("One alias per line, for example: whey = Whey protein powder").addTextArea((text) => {
      text.setPlaceholder("whey = Whey protein powder\ndark choc = Chocolate, dark, 70-85% cacao solids").setValue(this.plugin.settings.preferredFoods).onChange(async (value) => {
        this.plugin.settings.preferredFoods = value;
        this.plugin.clearLookupCache();
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 6;
    });
  }
};
function parseIngredientLine(line, ingredientDelimiter) {
  const ingredientLineRegex = buildIngredientLineRegex(ingredientDelimiter);
  const match = line.match(ingredientLineRegex);
  if (!match) {
    return null;
  }
  const amount = Number(match[3].replace(",", "."));
  const grams = toGrams(amount, match[4]);
  if (!Number.isFinite(grams) || grams <= 0) {
    return null;
  }
  return {
    prefix: match[1],
    foodName: match[2].trim(),
    amountText: match[3],
    unitText: normalizeUnit(match[4]),
    grams
  };
}
function buildIngredientLineRegex(ingredientDelimiter) {
  return new RegExp(`^(\\s*(?:[-*]\\s+)?)((?!total\\b).+?)${escapeRegExp(ingredientDelimiter)}(\\d+(?:[.,]\\d+)?)\\s*(g|gram|grams|kg|kilogram|kilograms)\\b(?:\\s*\\([^)]*kcal[^)]*\\))?(?:\\s*\\[\\? matched: .+\\])?\\s*$`, "i");
}
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function toGrams(amount, unit) {
  const normalizedUnit = unit.toLowerCase();
  if (normalizedUnit === "kg" || normalizedUnit === "kilogram" || normalizedUnit === "kilograms") {
    return amount * 1e3;
  }
  return amount;
}
function normalizeUnit(unit) {
  const normalizedUnit = unit.toLowerCase();
  if (normalizedUnit === "kg" || normalizedUnit === "kilogram" || normalizedUnit === "kilograms") {
    return "kg";
  }
  return "g";
}
function formatIngredientLine(ingredientLine, ingredientDelimiter, lookup, nutrition, settings) {
  const confidenceWarning = settings.markLowConfidenceMatches && lookup.needsReview ? ` [? matched: ${truncateText(lookup.matchedDescription, 72)}]` : "";
  return `${ingredientLine.prefix}${ingredientLine.foodName}${ingredientDelimiter}${ingredientLine.amountText}${ingredientLine.unitText} (${formatNutritionValues(nutrition, settings.includeMacros)})${confidenceWarning}`;
}
function formatNutritionValues(nutrition, includeMacros) {
  if (!includeMacros) {
    return `${formatKcal(nutrition.kcal)} kcal`;
  }
  return `${formatKcal(nutrition.kcal)} kcal, P ${formatMacro(nutrition.protein)}g, C ${formatMacro(nutrition.carbs)}g, F ${formatMacro(nutrition.fat)}g`;
}
function formatNutritionTotals(nutrition, includeMacros) {
  if (!includeMacros) {
    return `${formatKcal(nutrition.kcal)} kcal`;
  }
  return `${formatKcal(nutrition.kcal)} kcal, P ${formatMacro(nutrition.protein)}g, C ${formatMacro(nutrition.carbs)}g, F ${formatMacro(nutrition.fat)}g`;
}
function formatKcal(kcal) {
  return String(Math.round(kcal));
}
function formatMacro(macro) {
  return macro === null ? "?" : String(Math.round(macro * 10) / 10);
}
function formatConfidence(confidence) {
  return `${Math.round(confidence * 100)}%`;
}
function truncateText(value, maxLength) {
  if (value.length <= maxLength) {
    return value;
  }
  return `${value.slice(0, maxLength - 3)}...`;
}
